# ref: https://alacritty.org/config-alacritty.html

# [env]
# HOGEHOGE = "hogehoge"

[font]
size = 14

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[[keyboard.bindings]]
chars = "\u005c"
key = "¥"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.9
dimensions = { columns = 140, lines = 40 }

[window.padding]
x = 4
y = 4
