shell:
  program: /bin/zsh
  args:
    - --login
#    - --command
#    - "tmux attach || tmux"

#colors:
#  primary:
#    background: '#32302f'
#    foreground: '#ebdbb2'
#  normal:
#    black:   '#282828'
#    red:     '#cc241d'
#    green:   '#98971a'
#    yellow:  '#d79921'
#    blue:    '#458588'
#    magenta: '#b16286'
#    cyan:    '#689d6a'
#    white:   '#a89984'
#  bright:
#    black:   '#928374'
#    red:     '#fb4934'
#    green:   '#b8bb26'
#    yellow:  '#fabd2f'
#    blue:    '#83a598'
#    magenta: '#d3869b'
#    cyan:    '#8ec07c'
#    white:   '#ebdbb2'

font:
  size: 14  # フォントサイズ
  normal:
    family: 'HackGen Console NF'
    style: Regular
#  bold:
#    family: 'IBM Plex Mono'
#    style: Bold
#  italic:
#    family: 'IBM Plex Mono'
#    style: Italic
#  bold_italic:
#    family: 'IBM Plex Mono'
#    style: Bold Italic

window:
  padding:
    x: 4
    y: 4
  opacity: 0.9               # 背景を透過させる
#  decorations: full         # ボーダーとタイトルバーを表示する
#  startup_mode: Fullscreen  # フルスクリーンで起動する

