tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "rcmdnk/file"
cask "java"
cask "caskroom/versions/java8"
brew "bash", link: false
brew "embulk"
brew "ffmpeg", link: false
brew "git", link: false
brew "jq"
brew "mecab"
brew "mecab-ipadic"
brew "mysql", link: false
brew "nkf"
brew "nodebrew"
brew "postgresql"
brew "pyenv"
brew "r", link: false
brew "rbenv"
brew "sqlite"
brew "swftools"
brew "tree"
brew "watch"
brew "wget", link: false
brew "youtube-dl"
brew "zsh"
brew "zsh-git-prompt"
cask "5kplayer"
cask "astro"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iterm2"
cask "kindle"
cask "postico"
cask "rstudio"
cask "slack"
cask "visual-studio-code"
